### ISSUE TITLE
Strange push/pop behavior?

### ISSUE THREAD

**Issue by r2p2** [jgilchrist/emulator#3]
I was digging into the cpu_instr rom since the 01 special push af test case does not work on my emulator (very early development). After inspecting the test case code and debugging for hours, I am thinking that the test case should never work at all.

Then I saw that your emulator is able to get the test to pass so I used your debugger (thank you for that) to figure out why.

As far as I understand, if a `PUSH` is followed by a `POP` directly (no other interactions with the `SP` register), the `POP` should write the value, which was previously pushed, to the given register.

```
> step
| 0xC31D: PUSH BC (0xc5)
> regs
AF: 0000
BC: 1301
DE: 1200
HL: C304
SP: DFFB
PC: C31E
> step
| 0xC31E: POP AF (0xf1)
> regs
AF: 1300
BC: 1301
DE: 1200
HL: C304
SP: DFFD
PC: C31F
```

Why is AF `0x1300` and not `0x1301`?

**Comment by jgilchrist** [comment]
Hi @r2p2! Thanks so much for taking an interest, it's great to see other people finding this project useful 🙂

This particular case is something it took me a little while to figure out too. The issue here is that the `F` register behaves differently to the others - when writing, the least significant four bits are always masked out. You can see this in the following lines in `register.cc`:

```cpp
void FlagRegister::set(const u8 new_value) {
    val = new_value & 0xF0;
}
```

This applies to all writes to `F`, and if I recall correctly it fixed quite a few tests when I figured it out!

**Comment by r2p2** [comment]
It makes total sense knowing that it is also the flag register. Now I am wondering how long I would have needed to figure this out by myself. Thank you.. again.

**Comment by jgilchrist** [comment]
Any time! All the best with your emulator.
